###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: laravel-teste-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=car
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=123456
      ports:
        - "3002:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-teste-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3000:80"

    php-fpm:
      build:
        context: .
        dockerfile: php.dockerfile
      container_name: laravel-teste-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
